variable "pub_sub_1a_id" {}
variable "pub_sub_2b_id" {}
variable "pri_sub_3a_id" {}
variable "pri_sub_4b_id" {}
variable "pri_sub_5a_id" {}
variable "pri_sub_6b_id" {}
variable "igw" {}
variable "vpc_id" {}
variable "pub_sub_1a_cidr" {}
variable "pub_sub_2b_cidr" {}
variable "pri_sub_3a_cidr" {}
variable "pri_sub_4b_cidr" {}
variable "pri_sub_5a_cidr" {}
variable "pri_sub_6b_cidr" {}
